#Vault config
minDaysBeforeUpdateCert: 10
timeToSleep: 60
debug: false
#Vault config
vault:
  server: "http://127.0.0.1:8200"
  token: "hvs.7PH07dNglGbwNVRRgjByDMUe"

#Secrets
tls:
  kremlin_ru:
      namespaces:
        - "test"
        - "test2"
      secretName: "tls-secret"
      vaultSecretName: "test_k8s_sert"
      vaultPath: "kv"

  afanasiy_ru:
    namespaces:
      - "test"
    secretName: "test-secret"
    vaultSecretName: "test_k8s_sert"
    vaultPath: "kv"
